2024-04-04 13:43:57 | ERROR | stderr | [32mINFO[0m:     Shutting down
2024-04-04 13:43:58 | ERROR | stderr | [32mINFO[0m:     Finished server process [[36m13485[0m]
2024-04-04 13:43:58 | ERROR | stderr | [31mERROR[0m:    Traceback (most recent call last):
2024-04-04 13:43:58 | ERROR | stderr |   File "/home/mq/anaconda3/envs/son_llm/lib/python3.9/site-packages/starlette/routing.py", line 714, in lifespan
2024-04-04 13:43:58 | ERROR | stderr |     await receive()
2024-04-04 13:43:58 | ERROR | stderr |   File "/home/mq/anaconda3/envs/son_llm/lib/python3.9/site-packages/uvicorn/lifespan/on.py", line 137, in receive
2024-04-04 13:43:58 | ERROR | stderr |     return await self.receive_queue.get()
2024-04-04 13:43:58 | ERROR | stderr |   File "/home/mq/anaconda3/envs/son_llm/lib/python3.9/asyncio/queues.py", line 166, in get
2024-04-04 13:43:58 | ERROR | stderr |     await getter
2024-04-04 13:43:58 | ERROR | stderr | asyncio.exceptions.CancelledError
2024-04-04 13:43:58 | ERROR | stderr | 
2024-04-04 13:43:59 | ERROR | stderr | Exception ignored in: <module 'threading' from '/home/mq/anaconda3/envs/son_llm/lib/python3.9/threading.py'>
2024-04-04 13:43:59 | ERROR | stderr | Traceback (most recent call last):
2024-04-04 13:43:59 | ERROR | stderr |   File "/home/mq/anaconda3/envs/son_llm/lib/python3.9/threading.py", line 1477, in _shutdown
2024-04-04 13:43:59 | ERROR | stderr |     lock.acquire()
2024-04-04 13:43:59 | ERROR | stderr | KeyboardInterrupt:
2024-04-04 13:43:59 | ERROR | stderr | Error in atexit._run_exitfuncs:
2024-04-04 13:43:59 | ERROR | stderr | Traceback (most recent call last):
2024-04-04 13:43:59 | ERROR | stderr |   File "/home/mq/anaconda3/envs/son_llm/lib/python3.9/site-packages/torch/utils/data/_utils/__init__.py", line 45, in _set_python_exit_flag
2024-04-04 13:43:59 | ERROR | stderr |     global python_exit_status
2024-04-04 13:43:59 | ERROR | stderr | KeyboardInterrupt
